# -*- coding: utf-8 -*-
"""Random Forest Classifier using iris . ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRBNhjwdCBVikz0I4NlBcMQPjNVv-ydT
"""

import numpy as np
import pandas as pd

import sklearn

df = pd.read_csv("/Iris.csv")

df.head()

x= df[['SepalLengthCm','SepalWidthCm',	'PetalLengthCm',	'PetalWidthCm']]

y = df[['Species']]

from  sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)

len(y)

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators = 100, criterion = "gini")

clf.fit(x_train,y_train)

clf.predict(x_train)

clf.score(x_test,y_test)

